name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Foundry project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Show Forge version
        run: forge --version

      - name: Build project
        run: forge build

      - name: Run tests
        run: forge test -vvv